version: '3'

services:
  mongo_node1:
    image: mongo
    ports:
      - 30001:27017
    volumes:
      - $HOME/mongodb/data1:/data/db
    command: mongod --replSet ropod-replica
  mongo_node2:
    image: mongo
    ports:
      - 30002:27017
    volumes:
      - $HOME/mongodb/data2:/data/db
    command: mongod --replSet ropod-replica
  mongo_node3:
    image: mongo
    ports:
      - 30003:27017
    volumes:
      - $HOME/mongodb/data3:/data/db
    command: mongod --replSet ropod-replica

