version: '3'

services:
  mongorobot1:
    image: mongodb-robot:latest
    ports:
      - 27017:27017
    volumes:
      - $HOME/mongodb/data1:/data/db
      - $HOME/Desktop/logs/mongodb/executionlogs1:/var/executionlogs/
      - $PWD/src:/src
    networks:
      - mongocluster
    command: mongod --replSet sensor-replica
  mongodatacenter:
    image: mongodb-robot:latest
    ports:
      - 30002:27017
    volumes:
      - $HOME/mongodb/data2:/data/db
      - $HOME/Desktop/logs/mongodb/executionlogs2:/var/executionlogs/
      - $PWD/src:/src
    networks:
      - mongocluster
    command: mongod --replSet sensor-replica
    depends_on:
      - mongorobot1
networks:
  mongocluster:
    driver: bridge
