version: '3'

services:
  orientdbrobot1:
    image: orient-robot:latest
    ports:
      - 2424:2424
      - 2480:2480
    volumes:
      - $HOME/orientdb/databases1:/orientdb/databases
      - $HOME/orientdb/backup1:/orientdb/backup
      - $PWD/src:/src
    environment:
      - ORIENTDB_NODE_NAME=node1
      - ORIENTDB_ROOT_PASSWORD=admin
    command: /orientdb/bin/server.sh  -Ddistributed=true
  orientdbrobot2:
    image: orient-robot:latest
    ports:
      - 2425:2424
      - 2481:2480
    volumes:
      - $HOME/orientdb/databases2:/orientdb/databases
      - $HOME/orientdb/backup2:/orientdb/backup
      - $PWD/src:/src
    environment:
      - ORIENTDB_NODE_NAME=node2
      - ORIENTDB_ROOT_PASSWORD=admin
    command: /orientdb/bin/server.sh  -Ddistributed=true
  orientdbrobot3:
    image: orient-robot:latest
    ports:
      - 2426:2424
      - 2482:2480
    volumes:
      - $HOME/orientdb/databases3:/orientdb/databases
      - $HOME/orientdb/backup3:/orientdb/backup
      - $PWD/src:/src
    environment:
      - ORIENTDB_NODE_NAME=node3
      - ORIENTDB_ROOT_PASSWORD=admin
    command: /orientdb/bin/server.sh  -Ddistributed=true
