version: '3'

services:
  myphpcontainer:
    image: php:7.0-apache
    ports:
      - 8080:80
    volumes:
      - $HOME/.:/data
  mysqlcontainer:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
