version: '3'

services:
  arango-robot-agency1:
    container_name: arango-robot-agency1
    image: arango-robot:latest
    ports:
      - "8529"
    environment:
      - ARANGO_NO_AUTH=1
    command: arangod --server.endpoint tcp://0.0.0.0:8529 --agency.my-address=tcp://arango-robot-agency1:8529 --server.authentication false --agency.activate true --agency.size 3 --agency.supervision true

  arango-robot-agency2:
    container_name: arango-robot-agency2
    image: arango-robot:latest
    depends_on:
      - arango-robot-agency1
    ports:
      - "8529"
    environment:
      - ARANGO_NO_AUTH=1
    command: arangod --server.endpoint tcp://0.0.0.0:8529 --agency.my-address=tcp://arango-robot-agency2:8529 --server.authentication false --agency.activate true --agency.size 3 --agency.supervision true

  arango-robot-agency3:
    container_name: arango-robot-agency3
    image: arango-robot:latest
    depends_on:
      - arango-robot-agency2
    ports:
      - "8529"
    environment:
      - ARANGO_NO_AUTH=1
    command: /opt/wait-for-it.sh arango-robot-agency1:8529 -- arangod --server.endpoint tcp://0.0.0.0:8529 --agency.my-address=tcp://arango-robot-agency3:8529 --server.authentication false --agency.activate true --agency.size 3 --agency.endpoint tcp://arango-robot-agency1:8529 --agency.endpoint tcp://arango-robot-agency2:8529 --agency.endpoint tcp://arango-robot-agency3:8529 --agency.supervision true

  arango-robot-primary1:
    restart: always
    container_name: arango-robot-primary1
    image: arango-robot:latest
    depends_on:
      - arango-robot-agency3
    ports:
      - "8529"
    environment:
      - ARANGO_NO_AUTH=1
    command: /opt/wait-for-it.sh arango-robot-agency3:8529 -- arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8529 --cluster.my-address tcp://arango-robot-primary1:8529 --cluster.my-local-info db1 --cluster.my-role PRIMARY --cluster.agency-endpoint tcp://arango-robot-agency1:8529 --cluster.agency-endpoint tcp://arango-robot-agency2:8529 --cluster.agency-endpoint tcp://arango-robot-agency3:8529

  arango-robot-primary2:
    restart: always
    container_name: arango-robot-primary2
    image: arango-robot:latest
    depends_on:
      - arango-robot-agency3
    ports:
      - "8529"
    environment:
      - ARANGO_NO_AUTH=1
    command: /opt/wait-for-it.sh arango-robot-agency3:8529 -- arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8529 --cluster.my-address tcp://arango-robot-primary2:8529 --cluster.my-local-info db1 --cluster.my-role PRIMARY --cluster.agency-endpoint tcp://arango-robot-agency1:8529 --cluster.agency-endpoint tcp://arango-robot-agency2:8529 --cluster.agency-endpoint tcp://arango-robot-agency3:8529

  arango-robot-primary3:
    restart: always
    container_name: arango-robot-primary3
    image: arango-robot:latest
    depends_on:
      - arango-robot-agency3
    ports:
      - "8529"
    environment:
      - ARANGO_NO_AUTH=1
    command: /opt/wait-for-it.sh arango-robot-agency3:8529 -- arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8529 --cluster.my-address tcp://arango-robot-primary3:8529 --cluster.my-local-info db1 --cluster.my-role PRIMARY --cluster.agency-endpoint tcp://arango-robot-agency1:8529 --cluster.agency-endpoint tcp://arango-robot-agency2:8529 --cluster.agency-endpoint tcp://arango-robot-agency3:8529

  arango-robot-coordinator1:
    restart: always
    container_name: arango-robot-coordinator1
    image: arango-robot:latest
    depends_on:
      - arango-robot-primary1
      - arango-robot-primary2
      - arango-robot-primary3
    ports:
      - "11001:8529"
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
        - $HOME/Desktop/logs/arangodb/executionlogs1:/var/executionlogs/
        - $PWD/../src:/src
    command: /opt/wait-for-it.sh arango-robot-primary3:8529 -- arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8529 --cluster.my-address tcp://arango-robot-coordinator1:8529 --cluster.my-local-info coord1 --cluster.my-role COORDINATOR --cluster.agency-endpoint tcp://arango-robot-agency1:8529 --cluster.agency-endpoint tcp://arango-robot-agency2:8529 --cluster.agency-endpoint tcp://arango-robot-agency3:8529

  arango-robot-coordinator2:
    restart: always
    container_name: arango-robot-coordinator2
    image: arango-robot:latest
    depends_on:
      - arango-robot-primary1
      - arango-robot-primary2
      - arango-robot-primary3
    ports:
      - "11002:8529"
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
      - $HOME/Desktop/logs/arangodb/executionlogs2:/var/executionlogs/
      - $PWD/../src:/src
    command: /opt/wait-for-it.sh arango-robot-primary3:8529 -- arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8529 --cluster.my-address tcp://arango-robot-coordinator2:8529 --cluster.my-local-info coord2 --cluster.my-role COORDINATOR --cluster.agency-endpoint tcp://arango-robot-agency1:8529 --cluster.agency-endpoint tcp://arango-robot-agency2:8529 --cluster.agency-endpoint tcp://arango-robot-agency3:8529

  arango-robot-coordinator3:
    restart: always
    container_name: arango-robot-coordinator3
    image: arango-robot:latest
    depends_on:
      - arango-robot-primary1
      - arango-robot-primary2
      - arango-robot-primary3
    ports:
      - "11003:8529"
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
      - $HOME/Desktop/logs/arangodb/executionlogs3:/var/executionlogs/
      - $PWD/../src:/src
    command: /opt/wait-for-it.sh arango-robot-primary3:8529 -- arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8529 --cluster.my-address tcp://arango-robot-coordinator3:8529 --cluster.my-local-info coord3 --cluster.my-role COORDINATOR --cluster.agency-endpoint tcp://arango-robot-agency1:8529 --cluster.agency-endpoint tcp://arango-robot-agency2:8529 --cluster.agency-endpoint tcp://arango-robot-agency3:8529
